### ISSUE TITLE
References section not in full APA format?

### ISSUE THREAD

**Issue by a-hurst** [iamamutt/pandoc-apa#1]
First of all, thanks for creating this package! I've wanted a solution for writing papers where I could use Git to track changes instead of having a v0.2, v0.3, v0.3.5 after every round of changes and additions where changes aren't even readily visible.

I'm running into an issue where the reference section is not being formatted in the official APA style, and I'm not sure how to fix it. Specifically, the references all have a leading indent instead of a trailing one and the 'References' header is in bold (the APA style guide explicitly says it shouldn't be). The apa6 tex package examples seem to show it formatting it in the expected way, so I'm assuming it's a conflict between that package and something else in the provided template.

To illustrate, here's a screencap of a References section in a paper I was working on in Pages:

![screen shot 2018-06-27 at 11 24 26 am](https://user-images.githubusercontent.com/18648066/41980735-9606cfc8-79fd-11e8-9911-2f48ea39061f.png)

and here's how the same reference section looks when being rendered from a .bibtex file using pandoc-apa:

![screen shot 2018-06-27 at 11 32 12 am](https://user-images.githubusercontent.com/18648066/41980817-d6693b6e-79fd-11e8-9378-4800fe6abc90.png)

The References section in the apa-example.pdf is the same way. Is there anything in the template .tex file that you can think of that would do this?

Thanks in advance!

**Comment by iamamutt** [comment]
Thanks for pointing this out. It seems to be an issue with how pandoc-citeproc formats the CSL files. I've added a workaround to the template and the pdf example should now show the correct formatting.
